declare const BUILD_YEAR: string;
declare const BUILD_MONTH: string;
declare const BUILD_DAY: string;
declare const BUILD_TIME: string;
declare const SERVER_PORT: string;
declare const API_BASE_URL: string;
declare const CLIENT_NAME: string;
declare const APP_NAME: string;
declare const IS_PRODUCTION: string;
